"""Regenerate docs/FILE_MANIFEST.md from the extracted tree."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "backend"
OUT = ROOT / "docs" / "FILE_MANIFEST.md"

classifications = {
    "alembic": ("SHARED_DOMAIN", "Linear schema history required to recognize and migrate the existing AiROS database."),
    "app/core": ("SHARED_INFRASTRUCTURE", "Configuration, DB, auth security, middleware, Redis rate limiting, logging, and storage."),
    "app/dependencies": ("EMPLOYEE_DEPENDENCY", "JWT current-user and employee-compatible role enforcement."),
    "app/domain": ("SHARED_DOMAIN", "Canonical resource-state transitions used by employee maintenance/task work."),
    "app/models": ("EMPLOYEE_DEPENDENCY", "Complete related ORM metadata required by employee queries, foreign keys, and relationships."),
    "app/repositories": ("EMPLOYEE_DEPENDENCY", "Auth repositories and tenant/employee-scoped workspace reads."),
    "app/services": ("EMPLOYEE_DEPENDENCY", "Preserved auth, task, maintenance, allocation, occupancy, structure, and resource-state behavior."),
    "app/schemas": ("EMPLOYEE_REQUIRED", "Existing wire serializers plus explicit v1 contract exports."),
    "tests": ("EMPLOYEE_REQUIRED", "Extracted domain tests and employee OpenAPI compatibility tests."),
}

lines = ["# File manifest", "", "Generated by `scripts/build_file_manifest.py`. New architecture files have no original path.", "", "| Original | New | Classification | Reason / dependencies |", "|---|---|---|---|"]
for path in sorted(p for p in ROOT.rglob("*") if p.is_file() and "__pycache__" not in p.parts and ".pytest_cache" not in p.parts):
    rel = path.relative_to(ROOT).as_posix()
    if rel == "docs/FILE_MANIFEST.md":
        continue
    group = next((key for key in classifications if rel == key or rel.startswith(key + "/")), None)
    category, reason = classifications.get(group, ("EMPLOYEE_REQUIRED", "Independent runtime, deployment, test, or extraction documentation."))
    candidate = SOURCE / rel
    original = f"`backend/{rel}`" if candidate.exists() else "— (new)"
    lines.append(f"| {original} | `new_backend/{rel}` | {category} | {reason} |")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
